### ISSUE TITLE
Problems using .populateAll('films') from people

### ISSUE THREAD

**Issue by Haaragard** [amitmtrn/swapi-ts#1]
There seems to be an error with the populateAll, it tries to request for an httpss url.

my code:
```
SWApi.People.findBySearch([nome.value])
        .then(people => people.populateAll('films')) // breaks in here, not even pass.
        .then(people => people.resources.map(people => ({
            name: people.value.name,
            birth_year: people.value.birth_year,
            gender: people.value.gender,
            eye_color: people.value.eye_color,
            films: people.value.films.map(film => ({
                title: film.value.title,
                release_date: film.value.release_date
            }))
        })))
        .then(data => { people.value = data });
```

i'm using vue 3 with vite,  it's a new project.

The error:
![image](https://user-images.githubusercontent.com/15661230/149046136-d03a03bd-d122-4fb2-8523-30acafca10a9.png)

**Comment by mulztob** [comment]
This is a more general problem and can happen with any populateAll. Reason seems to be inside function populateSingle which does (twice)

`
....replace('http', 'https')
`
Issue should be fixable with:
`
....replace('http:', 'https:')
`

**Comment by mulztob** [comment]
@amitmtrn I've forked and added a PR here...
Please review and feel free to merge

**Comment by Haaragard** [comment]
@mulztob merging your PR will solve the issue, thanks.
